apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: radix-canary-golang
spec:
  replicas: 1
  selector:
    matchLabels:
      app: radix-canary-golang
  template:
    metadata:
      labels:
        app: radix-canary-golang
    spec:
      containers:
      - name: radix-canary-golang
        image: stianovrevage/radix-canary-golang:latest
        ports:
        - containerPort: 5000
        env:
          - name: LISTEN_PORT
            value: "5000"

---

apiVersion: v1
kind: Service
metadata:
  name: radix-canary-golang
  labels:
    app: radix-canary-golang
spec:
  ports:
  - port: 80
    targetPort: 5000
    protocol: TCP
    name: http
  selector:
    app: radix-canary-golang

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: radix-canary-ingress
spec:
  rules:
    - host: canary.playground-f-prometheus-7.dev.radix.equinor.com
      http:
        paths:
          - backend:
              serviceName: radix-canary-golang
              servicePort: 80
            path: /
#  tls:
#      - hosts:
#          - canary.playground-f-prometheus-7.dev.radix.equinor.com
#        secretName: domain-ssl-cert-key

---

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: radix-canary-golang
  labels:
    prometheus: prometheus
spec:
  endpoints:
  - interval: 5s
    port: http
  jobLabel: radix-canary-golang
  namespaceSelector:
    matchNames:
    - default
  selector:
    matchLabels:
      app: radix-canary-golang