apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: radix-canary-golang
spec:
  replicas: 1
  selector:
    matchLabels:
      app: radix-canary-golang
  template:
    metadata:
      labels:
        app: radix-canary-golang
    spec:
      containers:
      - name: radix-canary-golang
        image: stianovrevage/radix-canary-golang:latest
        ports:
        - containerPort: 5000
        env:
          - name: LISTEN_PORT
            value: "5000"

---

apiVersion: v1
kind: Service
metadata:
  annotations: 
    external-dns.alpha.kubernetes.io/hostname: "example.dev.radix.equinor.com."
    external-dns.alpha.kubernetes.io/ttl: "10"
  name: radix-canary-golang
  labels:
    app: radix-canary-golang
spec:
  ports:
  - port: 80
    targetPort: 5000
    protocol: TCP
    name: http
  selector:
    app: radix-canary-golang

---

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: radix-canary-golang
  labels:
    app: radix-canary-golang
spec:
  endpoints:
  - interval: 30s
    port: http
  jobLabel: radix-canary-golang
  namespaceSelector:
    matchNames:
    - any
  selector:
    matchLabels:
      app: radix-canary-golang