{
 "title": "Canary App Internal Stats",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Errors % last 60 minutes",
   "type": "singlestat",
   "gridPos": { "h": 13, "w": 3, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "rate(errors_total[60m]) / rate(requests_total[60m])"
    }
   ]
  },
  {
   "title": "Requests per second total",
   "type": "graph",
   "gridPos": { "h": 13, "w": 11, "x": 3, "y": 0 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    { "expr": "rate(requests_total[30s])" }
   ]
  },
  {
   "title": "Errors per second total",
   "type": "graph",
   "gridPos": { "h": 13, "w": 10, "x": 14, "y": 0 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    { "expr": "rate(errors_total[30s])" }
   ]
  }
 ]
}