apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: radix-canary-golang
spec:
  environments:
    - name: dev
      build:
        from: master
      authorization:
      - role: RadixAppAdmin
        groups:
        - "fg_radix_platform_development"
    - name: prod
      build:
        from: master
      authorization:
      - role: RadixAppAdmin
        groups:
        - "fg_radix_platform_development"
  components:
    - name: www
      src: "."
      public: true
      ports:
        - name: http
          port: 5000

