apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: radix-networkpolicy-canary
spec:
  environments:
    - name: egressrulestopublicdns
      build:
        from: main
      egressRules:
        - destinations:
            - "1.0.0.1/32"
            - "1.1.1.1/32"
            - "8.8.8.8/32"
            - "8.8.4.4/32"
          ports:
            - number: 53
              protocol: TCP
            - number: 53
              protocol: UDP
  components:
    - name: web
      src: "."
      monitoring: true
      ports:
        - name: http
          port: 5000
      publicPort: http
      resources:
        requests:
          memory: "20M"
          cpu: "100m"
        limits:
          memory: "20M"
          cpu: "1000m"
