apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: radix-networkpolicy-canary
spec:
  environments:
    - name: egressrulestopublicdns
      build:
        from: main
      egress:
        allowRadix: false
        rules:
        - destinations:
            - "1.0.0.1/32" #cloudflare
            - "1.1.1.1/32" #cloudflare
            - "8.8.8.8/32" #google
            - "8.8.4.4/32" #google
          ports:
            - port: 53
              protocol: TCP
            - port: 53
              protocol: UDP
    - name: oauthdenyall
      build:
        from: main
      egress:
        allowRadix: false
    - name: allowradix
      build:
        from: main
      egress:
        allowRadix: true
  jobs:
    - name: myjob
      readOnlyFileSystem: true
      src: ./jobsrc
      schedulerPort: 9000
      timeLimitSeconds: 1
  components:
    - name: redis
      readOnlyFileSystem: true
      src: ./redis
      secrets:
        - REDIS_PASSWORD
      ports:
        - name: redis
          port: 6379
      environmentConfig:
        - environment: oauthdenyall
          replicas: 1
        - environment: egressrulestopublicdns
          replicas: 0
        - environment: allowradix
          replicas: 0
    - name: web
      readOnlyFileSystem: true
      src: "."
      secrets:
        - NETWORKPOLICY_CANARY_PASSWORD
      monitoring: true
      ports:
        - name: http
          port: 5000
      publicPort: http
      variables:
        JOB_SCHEDULER_PORT: "9000"
        LISTENING_PORT: "5000"
        LOG_LEVEL: "info"
        PRETTY_LOG: "false"
      resources:
        requests:
          memory: "20M"
          cpu: "100m"
        limits:
          memory: "200M"
          cpu: "1000m"
      environmentConfig:
        - environment: oauthdenyall
          authentication:
            oauth2:
              clientId: 46e3125d-4465-4217-9a71-20b3dc91d9f4
              scope: openid profile email offline_access
              setXAuthRequestHeaders: true
              setAuthorizationHeader: true
              sessionStoreType: redis
              redisStore:
                connectionUrl: redis://redis:6379
