apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: radix-canary-golang
spec:
  environments:
    - name: dev
      build:
        from: master
    - name: prod
      build:
        from: release
  components:
    - name: www
      src: "."
      monitoring: true
      ports:
        - name: http
          port: 5000
      publicPort: http
