apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: radix-canary-golang
spec:
  environments:
    - name: dev
      build:
        from: master
    - name: prod
      build:
        from: release
  components:
    - name: www
      src: "."
      monitoring: true
      ports:
        - name: http
          port: 5000
      publicPort: http
      environmentConfig:
        - environment: dev
          resources:
            requests:
              memory: "20M"
              cpu: "100m"
            limits:
              memory: "20M"
              cpu: "10m"
        - environment: prod
          resources:
            requests:
              memory: "20M"
              cpu: "100m"
            limits:
              memory: "20M"
              cpu: "10m"
